### ISSUE TITLE
Join/Transfer to JuliaText Org?

### ISSUE THREAD

**Issue by oxinabox** [jbn/WordNet.jl#7]
Hi @jbn ,
We are trying to reboot the [JuliaText](https://github.com/JuliaText) github org as 
the place for NLP (/Computation Linquistics/etc) tooling for Julia.
Like what JuliaStats is for statistics.

It would be great to have you on-board.
Would you like to come join the `#natural-language` Slack channel (Invite at http://slackinvite.julialang.org/), and chat?

I think that WordNet be remains an important tool, and I think it would be good to have it in an organization repository.

It would help to start building a common definition package (Like LearnBase.jl, and StatsBase.jl),
which could do things like export the names like `sensekey` so multiple packages can use them happily.
(Eg right now one can't use CorpusLoaders.jl with WordNet.jl without a work around, as both export `sensekey`, WordNet as a function to geta WordNet sensekey directly, and CorpusLoaders as a function to find the sense of a word in a sense-annotated corpus.)

Anyway it would be cool to have you as a member of the org, and this package as one of the orgs packages.

**Comment by jbn** [comment]
Hey, @oxinabox.

I don't really get much time to play in Julia these days -- I hope I will again, soon. I'd also like to keep developing this package. But, realistically, I'll hold things up for want of time. For the sake of the Julia community, I'd be happy to transfer it to the org. 

Does that work, even without the additional help?

**Comment by oxinabox** [comment]
Ok,
I have invited you to join the org as  member.
I think that should give you the privilege to transfer this repository to the organization. (It will be in settings, in the danger zone).
METADATA.jl/Pkg/git will handle the moving of the repository without breaking. (I've done it before and it was fine).

When you transfer the repo, I believe you are presented with options for what privileges you want to give what other repo members. (Eg you can leave it with just you having commit/merge rights to master).
Your call on that.

**Comment by jbn** [comment]
After the transfer attempt, got a red flash message of,

> You don’t have the permission to create repositories on JuliaText

That docs seem to indicate that,

> the new owner will receive an email giving the option to accept or reject the transfer

but the error message didn't seem to reflect the same process. Let me know if you (or whoever is JuliaText's admin) received anything.

**Comment by oxinabox** [comment]
Ok, try again now.
There was a permission setting I needed to change to allow members to create repos.
I did not get an email.

**Comment by jbn** [comment]
Yikes. Sorry about the late response. Last week was one of those weeks you tell people were "a hell of a week" while really meaning "I'm ready for the world-ending asteroid now."

Seems like it worked. Oddly enough, I may get more involved soon. My dissertation ABM is now less of an ABM and more of a MCMC, so Julia is suddenly very attractive again!

Cheers.
